#!/bin/sh
alias ....='cd ../../..'
alias .....='cd ../../../..'

alias um="diskutil unmount Odysseus"

alias ho_local="ssh -p 768 garrett@192.168.1.102"
alias ka="open /Users/garrett/Downloads/killmouseaccel.app"
alias ls="ls -G"
alias pj="cd /Users/garrett/cal/61b/proj/61b-project-2/"

alias love="/Applications/love.app/Contents/MacOS/love"
alias o="open"
alias charcount="ruby -e \"puts gets.chomp.length\""

alias v=vagrant

alias gs="git status"
alias gd="git diff"
alias gdc="git diff --cached"
alias glp="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias gl="git log"
alias gpfo="git push --force-with-lease origin"
alias gpso="git push --set-upstream origin"

alias bi="bundle install"
alias be="bundle exec"
alias rs="rspec"
alias rss="rspec ."

# corrects to "yes" apparently
alias jest="nocorrect jest"

alias mtab="open -a MacVim"

alias iossim="open /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Applications/iPhone\ Simulator.app"

alias ss="cd /Volumes/Sidecar/staging"

ag-replace() {
  ag -l $1 | xargs perl -pi.bak -e "s/$1/$2/g"
}

gdm() {
  git diff `git merge-base --fork-point master` $@
}

alias gdmc="gdm --cached"
alias stripe-curl="curl --unix-socket ~/.stripeproxy"


pay-server-class() {
  awk -F'\t' '{
    if( ( ($4 == "c") || ($4 == "m")) && ($2 !~ "/?test/")) { 
      if($4 == "m") {
        gsub("class", "\033[0;32mmodule", $5);
      } 
      gsub(":", " ", $5); 
      gsub("\\.", "::", $5); 
      print "\033[0;33m" $5 "::" $1 ".\t\033[0;35m" $2 "\t" $3 
    }
  }' tags | fzf --ansi -d "\t" -n 1 | ruby -lne 'print $_.match(/([^ .]+)\./)[1]'
}

pay-server-symbol() {
  # skip first two lines
  awk -F'\t' 'NR > 2 {
    if($2 !~ "/?test/") { 
      gsub("class:", "", $5); 
      gsub("\\.", "::", $5); 
      if ($4 == "f") {
        delim = "#"
      } else if ($4 == "F") {
        delim = "."
      } else {
        delim = "::"
      }
      print "\033[0;33m" $5 delim $1 ".\t\033[0;35m" $2 "\t" $3 
    }
  }' tags | fzf --ansi -d "\t" -n 1 | ruby -lne 'print $_.match(/([^ .]+)\./)[1]'
}

alias pay-server-class-clip="pay-server-class | tr -d '\n' | pbcopy"
paytags() {
  find . \( -name 'build' -o -name 'vendor' -o -name 'migrations' \) -prune -o -name '*.rb' -print0 | xargs -0 -P 6 -n 3000 ripper-tags -f - | LC_ALL=C sort -u --radixsort > tags
}


paytags-with-rbi() {
  find . \( -name 'build' -o -name 'vendor' -o -name 'migrations' \) -prune -o -name '*.rb*' -print0 | xargs -0 -P 6 -n 3000 ripper-tags -f - | LC_ALL=C sort -u --radixsort > tags
}
shorten() {
  if [ $# -eq 0 ]; then
    echo "url=`pbpaste`" | stripe-curl http://go.northwest.corp.stripe.com/ -d name="" -d @- | pup '#link attr{value}' | tee >(pbcopy)
  else
    stripe-curl http://go.northwest.corp.stripe.com/ -d name="" -d $1 | pup '#link attr{value}' | tee >(pbcopy)
  fi
}

gfetch-branch() {
  git fetch origin +$1:$1
}
